[package]
name = "timer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gloo-timers = { version = "0.2.4", features = ["futures"] }
sycamore = { path = "../../packages/sycamore", features = ["suspense"] }

[lints]
workspace = true
