[package]
name = "motion"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
sycamore = { path = "../../packages/sycamore" }

[lints]
workspace = true
